### ISSUE TITLE
Build in XCode fails due to missing _config.h include file

### ISSUE THREAD

**Issue by ChristianWeyer** [T-Pau/Ready#10]
Hello dear developer team,

I just cloned the repo fresh onto my Mac.
After configuring the signing credentials and starting the build, I get this error:

![image](https://user-images.githubusercontent.com/888718/90337329-1b30b000-dfe2-11ea-827f-1baf3f76060d.png)

And indeed, I could not find this include file on my disk.
Any help? :-)

Thanks,
-Christian

**Comment by dillof** [comment]
Sigh, that was caused by a .gitignore file in the atari800 directory. Please try again.

**Comment by ChristianWeyer** [comment]
Awesome, thanks. Works now.

Danke dir, Dieter :-)
