### ISSUE TITLE
External controller support for ZX emulation

### ISSUE THREAD

**Issue by fmarquez** [T-Pau/Ready#14]
First of all, amazing project, and more amazing to share with the community, thanks!

It would be great if for the ZX family of computers, Joysticks can be emulated, specially to use external MFi controllers (already possible for C64 emulators)

Keep up the good work!

**Comment by dillof** [comment]
The ZX Spectrum +2 has two Sinclair type joystick ports built in, these are supported by Ready and work with MFi controllers.

Joystick adapters are not supported by Ready yet.

**Comment by fmarquez** [comment]
> The ZX Spectrum +2 has two Sinclair type joystick ports built in, these are supported by Ready and work with MFi controllers.
> 
> Joystick adapters are not supported by Ready yet.

Thanks, this is already quite useful!
