### ISSUE TITLE
Since iPadOS 13.3.1 App not work in device

### ISSUE THREAD

**Issue by lencio** [T-Pau/Ready#5]
**Describe the bug**
Since iPadOS 13.3.1 App not work in device

**To Reproduce**
Sideload or compile app and install from Xcode

**Device:**
 - Model: iPad Pro 12,9 2GEN
 iOS13.3.1

**Comment by lencio** [comment]
Should be a problem when used a non paid Apple ID developer with frameworks.

**Comment by lencio** [comment]
With paid Apple ID works.

**Comment by Tazdevil1723uk** [comment]
Is possible to change deb file? Or different way without a paid Apple ID developer?
